server:
  port: 9999
logging:
  level:
    org.springframework.web.client: DEBUG

#TODO: add ribbon configuration for *all* services used by api-gateway
#profanity:
#  ribbon:
#    eureka:
#      we don't want to user service discovery - yet
#      enabled: false
#    listOfServers: # list all available servers here